#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Запуск полибара
if type "polybar" > /dev/null; then
    polybar example &
fi

nitrogen --restore &

# Автоконфигурация мониторов
if xrandr | grep -q "HDMI-2 connected"; then
    xrandr --output HDMI-2 --auto --right-of eDP-1
else
    xrandr --output eDP-1 --auto
fi

# Автокиллер любых программ при закрытии окна
bspc subscribe node_remove | while read -r _ _ wid; do
    app=$(xprop -id "$wid" WM_CLASS 2>/dev/null | awk -F '"' '{print $4}')
    case "$app" in
        Steam|steam|lutris|discord)
            pkill -9 "$app"
            ;;
    esac
done &
